{
  "services": [
    {
      "type": "web",
      "name": "eagle-byte-server",
      "env": "node",
      "plan": "free",
      "buildCommand": "npm install",
      "startCommand": "node server.js",
      "envVars": [
        {
          "key": "NODE_VERSION",
          "value": "20.11.0"
        },
        {
          "key": "DB_URL",
          "sync": false
        },
        {
          "key": "ADMIN_EMAIL",
          "sync": false
        },
        {
          "key": "ADMIN_PASSWORD",
          "sync": false
        },
        {
          "key": "JWT_SECRET",
          "generateValue": true
        }
      ]
    }
  ]
}
